"""create products table

Revision ID: 4ac989360731
Revises: 
Create Date: 2026-04-22 09:39:05.138930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac989360731'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('profiles')
    op.alter_column('users', 'Login',
               existing_type=sa.NVARCHAR(length=50, collation='Cyrillic_General_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'Login',
               existing_type=sa.String(length=100),
               type_=sa.NVARCHAR(length=50, collation='Cyrillic_General_CI_AS'),
               existing_nullable=False)
    op.create_table('profiles',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('FullName', sa.NVARCHAR(length=255, collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Email', sa.NVARCHAR(length=255, collation='Cyrillic_General_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserId'], ['users.Id'], name=op.f('FK_profiles_users')),
    sa.PrimaryKeyConstraint('Id', name=op.f('PK__profiles__3214EC0756810232'))
    )
    op.drop_table('products')
    # ### end Alembic commands ###
